# Site wide configuration

title:            Steve Gills Blog
locale:           en_US
url:              
page:
  comments: true

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Steve Gill
  avatar: stevegill.jpeg
  bio: "Serial entrepeneur specialising in building business web apps, with over 20 years experience.
  Mainly involved in financial and grocery epos solutions. I design and lead the development of solutions I
  invest in. Strong believer in BDD and DDD."
  email: stevergill@remove-this.gmail.com
  disqus-shortname: stevergill
  twitter: stevergill #username
  facebook: stevergill #username
  google:
    plus: StephenGill1 #username
    analytics: UA-50426501-2
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: stevergill #username
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: stevergill
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
